# vm-glomar should be replaced by instance uuid
apiVersion: v1
kind: Secret
metadata:
  name: vm-glomar-cloudinit-userdata
type: Opaque
stringData:
  userdata: |
    #cloud-config
    password: password1
    chpasswd: { expire: False }
---
apiVersion: v1
kind: Secret
metadata:
  name: vm-glomar-cloudinit-networkdata
type: Opaque
stringData:
  networkdata: |
    version: 2
    ethernets:
      enp9s0:
        dhcp4: true
      enp10s0:
        dhcp4: true
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-glomar
  name: vm-glomar
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-glomar
        azorian.io/cluster: clementine
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: azorian.io/cluster
                    operator: In
                    values:
                      - clementine
              topologyKey: kubernetes.io/hostname
      domain:
        clock:
          utc: {}
          timer:
            kvm: {}
        cpu:
          model: host-passthrough
          sockets: 1
          cores: 4
          threads: 1
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
        resources:
          requests:
            memory: 16Gi
          limits:
            memory: 16Gi
        memory:
          hugepages:
            pageSize: "1Gi"
        devices:
          autoattachGraphicsDevice: false
          networkInterfaceMultiqueue: true
          disks:
            - name: boot-disk
              disk:
                bus: virtio
                pciAddress: "0000:03:00.0"
            - name: cloud-init-disk
              disk:
                bus: virtio
                pciAddress: "0000:04:00.0"
                readonly: true
          interfaces:
            - name: default
              bridge: {}
              pciAddress: "0000:09:00.0"
              ports:
                - name: ssh
                  port: 22
            - name: sriov-net
              sriov: {}
              pciAddress: "0000:0a:00.0"
      volumes:
        - name: boot-disk
          dataVolume:
            name: boot-disk-node1
        - name: cloud-init-disk
          cloudInitNoCloud:
            secretRef:
              name: vm-glomar-cloudinit-userdata
            networkDataSecretRef:
              name: vm-glomar-cloudinit-networkdata
      networks:
        - name: default
          pod: {}
        - name: sriov-net
          multus:
            networkName: sriov-default
  dataVolumeTemplates:
    - metadata:
        name: boot-disk-node1
      spec:
        pvc:
          volumeMode: Block
          storageClassName: csi-lvm-sc-linear
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
        source:
          registry:
            url: "docker://quay.io/port/kubevirt-images:ubuntu-focal"
# FROM scratch
# ADD --chown=107:107 https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img /disk/