apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
spec:
  terminationGracePeriodSeconds: 30
  hostname: "myvmi"
  subdomain: "mysubdomain"
  domain:
    clock:
      utc: {}
      timer:
        kvm: {}
    cpu:
      model: host-passthrough
      sockets: 2
      cores: 1
      threads: 1
      dedicatedCpuPlacement: true
      isolateEmulatorThread: true
    # firmware:
    #   kernelBoot:
    #     kernelArgs: systemd.cpu_affinity="0,1"
    #     #BOOT_IMAGE=/boot/vmlinuz-4.13.9-300.fc27.x86_64 root=UUID=d020d197-657b-4030-bde5-0db8417bc39c ro no_timer_check console=tty1 console=ttyS0,115200n8 LANG=en_US.UTF-8
    #   bootloader:
    #     efi:
    #       secureBoot: false
    resources:
      limits:
        memory: 2Gi
    memory:
      hugepages:
        pageSize: "1Gi"
    devices:
      autoattachGraphicsDevice: false
      disks:
        - name: bootdisk
          disk:
            bus: virtio
        - name: emptydisk
          disk:
            bus: virtio
        - name: cloudinitdisk
          disk:
            bus: virtio
      interfaces:
        - name: default
          bridge: {}
          ports:
            - name: ssh
              port: 22
        - name: sriov-net
          sriov: {}
  networks:
    - name: default
      pod: {}
    - name: sriov-net
      multus:
        networkName: sriov-default
  volumes:
    - name: bootdisk
      dataVolume:
        name: registry-image-datavolume-lvm
    - name: emptydisk
      emptyDisk:
        capacity: "2Gi"
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
