apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-macvlan
spec:
  terminationGracePeriodSeconds: 30
  hostname: "myvmi"
  subdomain: "mysubdomain"
  domain:
    clock:
      utc: {}
      timer:
        kvm: {}
    cpu:
      model: host-passthrough
      sockets: 1
      cores: 2
      threads: 1
      dedicatedCpuPlacement: true
      isolateEmulatorThread: true
    resources:
      limits:
        memory: 2Gi
    memory:
      hugepages:
        pageSize: "1Gi"
    devices:
      autoattachGraphicsDevice: false
      disks:
        - name: bootdisk
          disk:
            bus: virtio
        - name: emptydisk
          disk:
            bus: virtio
        - name: cloudinitdisk
          disk:
            bus: virtio
      interfaces:
        - name: default
          bridge: {}
          pciAddress: "0000:09:00.0"
          ports:
            - name: ssh
              port: 22
        - name: test1
          bridge: {}
          pciAddress: "0000:0a:00.0"
  networks:
    - name: default
      pod: {}
    - name: test1
      multus:
        networkName: macvlan-default
  volumes:
    - name: bootdisk
      containerDisk:
        image: quay.io/port/kubevirt-images:ubuntu-focal-perms
    - name: emptydisk
      emptyDisk:
        capacity: "2Gi"
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: password1
          chpasswd: { expire: False }
        networkData: |-
          version: 2
          ethernets:
            enp9s0:
              dhcp4: true
            enp10s0:
              dhcp4: true
