# This example assumes you are using a default storage class
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: registry-image-datavolume
spec:
  source:
    registry:
      url: "docker://kubevirt/fedora-cloud-registry-disk-demo"
  pvc:
    volumeMode: Block
    storageClassName: rook-ceph-ec-block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
---
# This example assumes you are using a default storage class
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: registry-image-datavolume-lvm
spec:
  source:
    registry:
      url: "docker://kubevirt/fedora-cloud-registry-disk-demo"
  pvc:
    volumeMode: Block
    storageClassName: csi-lvm-sc-linear
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi