apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ecpool
  namespace: rook-ceph
spec:
  failureDomain: osd
  erasureCoded:
    dataChunks: 2
    codingChunks: 1
  deviceClass: ssd
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ecpool-metadata
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 2
  deviceClass: ssd
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 3
  deviceClass: nvme