apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: rook-ceph-tools
        image: rook/ceph:master
        command: ["/tini"]
        args: ["-g", "--", "/usr/local/bin/toolbox.sh"]
        imagePullPolicy: IfNotPresent
        env:
          - name: ROOK_CEPH_USERNAME
            valueFrom:
              secretKeyRef:
                name: rook-ceph-mon
                key: ceph-username
          - name: ROOK_CEPH_SECRET
            valueFrom:
              secretKeyRef:
                name: rook-ceph-mon
                key: ceph-secret
        volumeMounts:
          - mountPath: /etc/ceph
            name: ceph-config
          - name: mon-endpoint-volume
            mountPath: /etc/rook
      volumes:
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
            - key: data
              path: mon-endpoints
        - name: ceph-config
          emptyDir: {}
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 5
# To get ceph healthy on less than three nodes:
# POD=$(kubectl -n rook-ceph get pod -l app=rook-ceph-tools -o name | awk -F '/' '{ print $NF }')
# kubectl -n rook-ceph exec -it ${POD} -- bash -c "ceph osd getcrushmap | crushtool -d - > /tmp/crush.map"
# kubectl -n rook-ceph exec -it ${POD} -- bash -c 'sed -i "s/step chooseleaf firstn 0 type host/step chooseleaf firstn 0 type osd/g" /tmp/crush.map'
# kubectl -n rook-ceph exec -it ${POD} -- bash -c 'crushtool -c /tmp/crush.map -o /tmp/crush.map.compiled'
# kubectl -n rook-ceph exec -it ${POD} -- bash -c 'ceph osd setcrushmap -i /tmp/crush.map.compiled'
# kubectl -n rook-ceph exec -it ${POD} -- bash -c "rm -v /tmp/crush.map"