apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-default
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "bond0",
      "mode": "bridge",
      "ipam": {
          "type": "dhcp"
      }
    }'

# cat <<EOF | kubectl apply -f -
# apiVersion: v1
# kind: Pod
# metadata:
#   name: samplepod-macvlan
#   annotations:
#     k8s.v1.cni.cncf.io/networks: macvlan-default
# spec:
#   nodeName: singapore
#   containers:
#   - name: samplepod
#     command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
#     image: alpine
# ---
# EOF