apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 192.168.1.1
      peer-asn: 64512
      my-asn: 64513
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 172.16.32.0/20
# Unifi USG config (sites/default/config.gateway.json):
# {
#   "protocols": {
#     "bgp": {
#       "64512": {
#         "neighbor": {
#           "192.168.1.4": {
#             "remote-as": "64513"
#           },
#           "192.168.1.100": {
#             "remote-as": "64513"
#           },
#           "192.168.1.2": {
#             "remote-as": "64513"
#           }
#         },
#         "parameters": {
#           "router-id": "192.168.1.1"
#         }
#       }
#     }
#   }
# }