apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubevirt/kubevirt/releases/download/v0.42.1/kubevirt-operator.yaml
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.35.0/cdi-operator.yaml
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.35.0/cdi-cr.yaml
- kubevirt.yaml
